ahoyapi: v2
commands:
  config:
    cmd: |
      cp ../master/.env ./
      cp ../master/lechuga/lechuga.sqlite ./lechuga/

  capture:
    cmd: |
      cp .env ../master/
      cp lechuga/lechuga.sqlite ../master/lechuga/
